# Generated by Django 5.1.3 on 2024-12-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionary", "0007_alter_dictionary_slug_alter_dictionaryentry_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalDictionarySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.URLField()),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("rate_limit", models.PositiveIntegerField(default=1000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_dictionary_sources",
                        to="dictionary.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Dictionary Source",
                "verbose_name_plural": "External Dictionary Sources",
            },
        ),
        migrations.CreateModel(
            name="WordDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.TextField()),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_dictionary_definitions",
                        to="dictionary.dictionaryentry",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_dictionary_definitions",
                        to="language_resources.externaldictionarysource",
                    ),
                ),
                (
                    "target_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_dictionary_definitions",
                        to="dictionary.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word Definition",
                "verbose_name_plural": "Word Definitions",
            },
        ),
    ]
