# Generated by Django 5.1.3 on 2024-12-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_userprofile_options_remove_customuser_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="slug"),
        ),
    ]
