# Generated by Django 5.1.3 on 2024-12-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
    ]
