# Generated by Django 5.1.3 on 2024-12-19 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_entries",
                    models.IntegerField(
                        default=0, verbose_name="total number of dictionary entries"
                    ),
                ),
                (
                    "total_examples",
                    models.IntegerField(
                        default=0, verbose_name="total number of user-added examples"
                    ),
                ),
                (
                    "last_entry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="last entry date"
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0, verbose_name="current streak in days"
                    ),
                ),
                (
                    "max_streak",
                    models.IntegerField(
                        default=0, verbose_name="highest streak in days"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Statistic",
                "verbose_name_plural": "User Statistics",
            },
        ),
    ]
