# Generated by Django 5.1.3 on 2024-12-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatistics",
            name="weekly_entries",
            field=models.IntegerField(
                default=0, verbose_name="weekly number of entries"
            ),
        ),
        migrations.AddField(
            model_name="userstatistics",
            name="weekly_examples",
            field=models.IntegerField(
                default=0, verbose_name="weekly number of user-added examples"
            ),
        ),
        migrations.AlterField(
            model_name="userstatistics",
            name="total_entries",
            field=models.IntegerField(default=0, verbose_name="total number entries"),
        ),
    ]
