# Generated by Django 5.1.3 on 2024-12-12 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField(verbose_name="example sentence")),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="source"
                    ),
                ),
            ],
            options={
                "verbose_name": "Example",
                "verbose_name_plural": "Examples",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="language"
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.CreateModel(
            name="DictionaryFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="dictionary folder name"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="dictionary.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dictionary Folder",
                "verbose_name_plural": "Dictionary Folders",
            },
        ),
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="dictionary name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="dictionary description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictionaries",
                        to="dictionary.dictionaryfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dictionary",
                "verbose_name_plural": "Dictionaries",
            },
        ),
        migrations.CreateModel(
            name="DictionaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(max_length=255, verbose_name="dictionary entry"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="dictionary.dictionary",
                    ),
                ),
                (
                    "examples",
                    models.ManyToManyField(
                        related_name="entries", to="dictionary.example"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dictionary Entry",
                "verbose_name_plural": "Dictionary Entries",
            },
        ),
        migrations.CreateModel(
            name="Meaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="word meaning")),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meanings",
                        to="dictionary.dictionaryentry",
                    ),
                ),
                (
                    "target_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meanings",
                        to="dictionary.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meaning",
                "verbose_name_plural": "Meanings",
            },
        ),
        migrations.AddConstraint(
            model_name="dictionary",
            constraint=models.UniqueConstraint(
                fields=("folder", "name"), name="unique_dictionary_per_folder"
            ),
        ),
        migrations.AddConstraint(
            model_name="dictionaryentry",
            constraint=models.UniqueConstraint(
                fields=("dictionary", "word"), name="unique_entry_per_dictionary"
            ),
        ),
        migrations.AddConstraint(
            model_name="dictionaryfolder",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_folder_per_user"
            ),
        ),
    ]
