# Generated by Django 5.1.3 on 2024-12-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0004_dictionary_slug_dictionaryentry_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionary",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="dictionaryfolder",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="language",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
    ]
