# Generated by Django 5.1.3 on 2024-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0006_alter_dictionaryfolder_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionary",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, unique=True, verbose_name="slug"
            ),
        ),
    ]
