# Generated by Django 5.1.3 on 2024-12-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0007_alter_dictionary_slug_alter_dictionaryentry_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionaryentry",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="entry notes"),
        ),
    ]
