# Generated by Django 5.1.3 on 2024-12-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dictionary",
            "0009_alter_dictionary_slug_alter_dictionaryentry_slug_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="examples",
        ),
        migrations.AddField(
            model_name="example",
            name="entry",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examples",
                to="dictionary.dictionaryentry",
            ),
        ),
    ]
