# Generated by Django 5.1.3 on 2024-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0011_alter_example_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Georgian", "Georgian"),
                    ("Korean", "Korean"),
                    ("French", "French"),
                    ("Spanish", "Spanish"),
                    ("German", "German"),
                    ("Mandarin", "Chinese Simplified"),
                ],
                max_length=15,
            ),
        ),
    ]
