# Generated by Django 5.1.3 on 2024-12-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0012_alter_language_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionaryentry",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="entry_images/"),
        ),
    ]
