# Generated by Django 5.1.3 on 2025-01-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0013_dictionaryentry_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionary",
            name="accessibility",
            field=models.CharField(
                choices=[("Public", "Public"), ("Private", "Private")],
                default="Public",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dictionaryfolder",
            name="accessibility",
            field=models.CharField(
                choices=[("Public", "Public"), ("Private", "Private")],
                default="Public",
                max_length=10,
            ),
        ),
    ]
